### ISSUE TITLE
loadExtendScript in cep-interface fails

### ISSUE THREAD

**Issue by longy26** [fusepilot/create-cep-extension#10]
### Description

`loadExtendscript('index.jsx');` fails.

### Expected behavior

It should load the Extendscript.

### Actual behavior

Tell us what actually happens.

When i try to use  `loadExtendscript('index.jsx');` in cep-interface the command `this.getOSInformation()` fails. 

Error: TypeError: Cannot read property 'getOSInformation' of undefined

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls create-cep-extension-scripts` (if you haven’t ejected): create-cep-extension-scripts@1.0.0-beta.10
2. `node -v`: v8.5.0
3. `npm -v`: 5.3.0

Then, specify:

1. Operating system: MacOS
2. Browser and version: Indesign

**Comment by fusepilot** [comment]
Thanks for the report! I'll look into to it as soon as I have some free time.

**Comment by fusepilot** [comment]
Closed with b99368000f66daf72a08e718d69d919bf5bf8e86. Released in `cep-interface@1.0.0-beta.7`.
