### ISSUE TITLE
`build/manifest.xml` not editable

### ISSUE THREAD

**Issue by sebgrizzly** [fusepilot/create-cep-extension#19]
### Description
`build/manifest.xml` not editable. I can't change the width and height of the photoshop panel. its hardcoded in:
 `create-cep-extension/packages/create-cep-extension-scripts/scripts/templates/manifest.js`

[see here](https://github.com/fusepilot/create-cep-extension/blob/master/packages/create-cep-extension-scripts/scripts/templates/manifest.js)

### Expected behavior
It would be nice if you could serve a config file to setup the manifest.xml.

Thanks and regards Sebi

**Comment by sbaden** [comment]
I've run into the same issue. I can't change the name of the extension in the manifest even after adding it to the .env file. Also, I can't add additional <script> tags in the manifest to include other supporting .jsx files.  Everytime I make a change to the manifest it reverts back after restarting with npm start.
<img width="959" alt="Screen Shot 2019-06-05 at 3 07 56 PM" src="https://user-images.githubusercontent.com/13071140/58993954-e1d89f80-87a3-11e9-903d-be3084adce42.png">
<img width="1644" alt="Screen Shot 2019-06-05 at 3 08 26 PM" src="https://user-images.githubusercontent.com/13071140/58993955-e1d89f80-87a3-11e9-9f63-371ede11b0ec.png">
