### ISSUE TITLE
Cannot get npm run to work

### ISSUE THREAD

**Issue by dvoina** [fusepilot/create-cep-extension#21]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Can you reproduce the problem with latest npm?
Yes

### Description
It sees that there are some unresolved (?) dependencies with the latest version.  

`
Oces-MacBook-Pro:burux2 wfps$ create-cep-extension burux2
/usr/local/lib/node_modules/create-cep-extension
Creating a new CEP extension in /Users/wfps/burux/burux2/burux2/burux2.

Installing packages. This might take a couple minutes.
Installing react, react-dom, and create-cep-extension-scripts...

> fsevents@1.1.2 install /Users/wfps/burux/burux2/burux2/burux2/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.11.1 (node-v59 ABI) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:85:
../src/methods.cc:14:12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  handler->Call(3, argv);
           ^
../../nan/nan.h:1618:3: note: 'Call' has been explicitly marked deprecated here
  Call(int argc, v8::Local<v8::Value> argv[]) const {
  ^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/wfps/burux/burux2/burux2/burux2/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/wfps/burux/burux2/burux2/burux2/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> zxp-provider@1.2.0 postinstall /Users/wfps/burux/burux2/burux2/burux2/node_modules/zxp-provider
> node ./postInstall.js

Updating permissions for /bin/osx...
Permissions for /bin/osx set to 755.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ react@16.3.2
+ create-cep-extension-scripts@1.0.0-beta.25
+ react-dom@16.3.2
added 1428 packages from 799 contributors in 120.438s

Success! Created burux2 at /Users/wfps/burux/burux2/burux2/burux2
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm run archive
    Creates a ZXP archive of the build to deploy to your extension users.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd burux2
  npm start

Happy hacking!

`

Although it seems that the creation of the extension worked, running `npm start` yields:
`
Oces-MacBook-Pro:burux2 wfps$ npm start

> burux2@0.1.0 start /Users/wfps/burux/burux2/burux2
> create-cep-extension-scripts start

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module './templates/.debug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/wfps/burux/burux2/burux2/node_modules/create-cep-extension-scripts/scripts/cep.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/wfps/burux/burux2/burux2/node_modules/create-cep-extension-scripts/scripts/start.js:43:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
start
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! burux2@0.1.0 start: `create-cep-extension-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the burux2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wfps/.npm/_logs/2018-04-19T12_35_36_915Z-debug.log
`

### Expected behavior

Created extension and able to start the development server.

### Actual behavior

Error on startup

### Environment

burux2@0.1.0 /Users/wfps/burux/burux2/burux2
└── create-cep-extension-scripts@1.0.0-beta.25 
node: v9.11.1
npm: 5.8.0

1. Operating system: macOS 10.11
2. Browser and version: n/a

### Reproducible Demo

Follow the steps described on the github page.

**Comment by phlexib** [comment]
same error for me.
OS : macOS 10.12.6
node : 8.9.4

**Comment by timolins** [comment]
I'm experiencing the same issue. Also on macOS with node 10 & yarn.

**Comment by fusepilot** [comment]
Could you try now with `create-cep-extension@1.0.0-beta.20`?

I wasn't able to reproduce locally. NPM currently finds and download the `fsevents` pre built binary fine. So I republished all of the packages and updated a few dependencies. Hopefully that flushes out the problem. Let me know.

**Comment by timolins** [comment]
Looking good! Works just fine for me now!

**Comment by dvoina** [comment]
It works!
Tested on 10.11 and 10.12.
