### ISSUE TITLE
Template .env file typo

### ISSUE THREAD

**Issue by jmgirven** [fusepilot/create-cep-extension#6]
Your [template .env file](https://github.com/fusepilot/create-cep-extension/blob/c154b6c80b300cf61edb88cd6d91a42574998212/packages/create-cep-extension-scripts/template/.env), should it say e.g: `CCERTIFICATE_PASSWORD` or should it be `CERTIFICATE_PASSWORD`? I assume the latter.

**Comment by fusepilot** [comment]
Yes, those were typos. Thanks.
